### ISSUE TITLE
Why not give a example for revel?

### ISSUE THREAD

**Issue by xpbliss** [jeevatkm/jwtauth#1]
It's a good work!
why not give a simple example for revle?

**Comment by jeevatkm** [comment]
Thanks, sure will do.

**Comment by jeevatkm** [comment]
Added example application here `example/jwtauth-example`

**Comment by xpbliss** [comment]
ERROR   jwt.go:264: Key file open error [private.rsa]
Where are the "private.rsa" and "public.rsa"  in the example?

**Comment by jeevatkm** [comment]
Pushed example app keys files into repo. Also added command details for generating new key files.

**Comment by jeevatkm** [comment]
Just thought to inform you.

Implemented JWT signing methods HS256, HS384, HS512, RS256, RS384, RS512, ES256, ES384 and ES512. Example application updated for this.
